//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_club
{
    using System;
    using System.Collections.Generic;
    
    public partial class abonnement
    {
        public abonnement()
        {
            this.payements = new HashSet<payement>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<int> id_sport { get; set; }
        public Nullable<int> id_abonne { get; set; }
    
        public virtual adherent adherent { get; set; }
        public virtual sport sport { get; set; }
        public virtual ICollection<payement> payements { get; set; }
    }
}
