//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_club
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_clubEntities : DbContext
    {
        public Gestion_clubEntities()
            : base("name=Gestion_clubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abonnement> abonnements { get; set; }
        public virtual DbSet<adherent> adherents { get; set; }
        public virtual DbSet<payement> payements { get; set; }
        public virtual DbSet<sport> sports { get; set; }
    }
}
