//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_club
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_clubEntities1 : DbContext
    {
        public Gestion_clubEntities1()
            : base("name=Gestion_clubEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<abonnement> abonnements { get; set; }
        public DbSet<adherent> adherents { get; set; }
        public DbSet<payement> payements { get; set; }
        public DbSet<sport> sports { get; set; }
    }
}
