//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_club
{
    using System;
    using System.Collections.Generic;
    
    public partial class payement
    {
        public int id { get; set; }
        public Nullable<int> id_abonnement { get; set; }
        public Nullable<System.DateTime> mois_courant { get; set; }
        public Nullable<byte> payer { get; set; }
    
        public virtual abonnement abonnement { get; set; }
    }
}
