//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class abonnement
    {
        public abonnement()
        {
            this.payements = new HashSet<payement>();
        }
    
        public int id { get; set; }
        public Nullable<int> type_sport { get; set; }
        public Nullable<int> id_abonne { get; set; }
        public string date_debut { get; set; }
    
        public virtual adherent adherent { get; set; }
        public virtual sport sport { get; set; }
        public virtual ICollection<payement> payements { get; set; }
    }
}
