//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_clubEntities : DbContext
    {
        public Gestion_clubEntities()
            : base("name=Gestion_clubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abonnement> abonnements { get; set; }
        public virtual DbSet<adherent> adherents { get; set; }
        public virtual DbSet<payement> payements { get; set; }
        public virtual DbSet<sport> sports { get; set; }
    }
}
