//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payement
    {
        public int id { get; set; }
        public Nullable<byte> payer { get; set; }
        public string mois_courant { get; set; }
        public Nullable<int> id_abonnement { get; set; }
    
        public virtual abonnement abonnement { get; set; }
    }
}
