//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sport
    {
        public sport()
        {
            this.abonnements = new HashSet<abonnement>();
        }
    
        public int id { get; set; }
        public string libele { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<abonnement> abonnements { get; set; }
    }
}
